### ISSUE TITLE
problem while training

### ISSUE THREAD

**Issue by l6chen** [zeroone-universe/RealTimeBWE#1]
Hello,

when I attempt to reproduce your work, I got these error:

Sanity Checking DataLoader 0:   0%|                                                                                                       | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/ma-user/work/c00573026/AISR/RealTimeBWE-master/main.py", line 45, in <module>
    main(config)
  File "/home/ma-user/work/c00573026/AISR/RealTimeBWE-master/main.py", line 39, in main
    trainer.fit(rtbwe_train, rtbwe_datamodule)
  File "/home/ma-user/anaconda3/envs/seanet_clf/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 520, in fit
    call._call_and_handle_interrupt(
  File "/home/ma-user/anaconda3/envs/seanet_clf/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/anaconda3/envs/seanet_clf/lib/python3.11/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 92, in launch
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/anaconda3/envs/seanet_clf/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 559, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/ma-user/anaconda3/envs/seanet_clf/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 935, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/home/ma-user/anaconda3/envs/seanet_clf/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 976, in _run_stage
    self._run_sanity_check()
  File "/home/ma-user/anaconda3/envs/seanet_clf/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 1005, in _run_sanity_check
    val_loop.run()
  File "/home/ma-user/anaconda3/envs/seanet_clf/lib/python3.11/site-packages/pytorch_lightning/loops/utilities.py", line 174, in _decorator
    return loop_run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/anaconda3/envs/seanet_clf/lib/python3.11/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 115, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "/home/ma-user/anaconda3/envs/seanet_clf/lib/python3.11/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 375, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_kwargs.values())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/anaconda3/envs/seanet_clf/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 288, in _call_strategy_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/anaconda3/envs/seanet_clf/lib/python3.11/site-packages/pytorch_lightning/strategies/ddp.py", line 337, in validation_step
    return self.model(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/anaconda3/envs/seanet_clf/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/anaconda3/envs/seanet_clf/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/anaconda3/envs/seanet_clf/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/anaconda3/envs/seanet_clf/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/anaconda3/envs/seanet_clf/lib/python3.11/site-packages/pytorch_lightning/overrides/base.py", line 102, in forward
    return self._forward_module.validation_step(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/work/c00573026/AISR/RealTimeBWE-master/train.py", line 93, in validation_step
    wav_bwe = self.forward(wav_nb)
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/work/c00573026/AISR/RealTimeBWE-master/train.py", line 41, in forward
    x = self.resampler(x)
        ^^^^^^^^^^^^^^
  File "/home/ma-user/anaconda3/envs/seanet_clf/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'RTBWETrain' object has no attribute 'resampler'

Can you offer the resampler method?

**Comment by zeroone-universe** [comment]
Hi, thank you for your interest on this repo.
My latest commit, which tagged with 0.1.0, have resolved this issue, and it works fine for me.
If you give it a try and encounter any further issues, please let me know.

Best.

**Comment by l6chen** [comment]
Yeah, I added the resampler and it works.
